### ISSUE TITLE
Lessons in Building apps on low-latency apps on historical data insights

### ISSUE THREAD

**Issue by Who828** [graphqlsydney/graphqlsydney#23] opened 2023-04-03 07:24 UTC
### Brief summary of the talk content:
In this talk, we will show how you can surface historical insights from Snowflake via a transactional PostgreSQL layer to real-time actions in your apps. We will show how data APIs radically simplify this analytical + transactional architecture.

### Takeaways: 

1. Example use cases of “translytical” workloads
2. Making intelligent real-time decisions based on insights from historical data
3. Advantage of using data APIs to fetch information from a data warehouse

### Details:
Which month's meetup you would like to present at - April/May
Will the talk be given in-person or online - Online
Length of talk - 25 mins talk, 5 mins Q&A
Where you can be found on the internet (e.g. personal website, social media account links etc) - http://linkedin.com/in/who828/

**Comment by mbuhot** [comment] 2024-03-11 08:26
Closing this one as it's been open for close to 12 months.
If you're still interested in giving a talk, please provide an updated social media profile (the LinkedIn link in the issue isn't working for me, nor the twitter profile @Who828) and re-open the issue. Thanks!

**Closed as completed by mbuhot** 2024-03-11 08:26 UTC
Labels: presentation
